<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2009-09-25 13:14

$extensionClassesPath = t3lib_extMgm::extPath('solr') . 'Classes/';
return array(
	'tx_solr_additionalindexerinterface' => $extensionClassesPath . 'AdditionalIndexerInterface.php',
	'tx_solr_indexer' => $extensionClassesPath . 'Indexer.php',
	'tx_solr_pagedocumentpostprocessorinterface' => $extensionClassesPath . 'PageDocumentPostProcessorInterface.php',
	'tx_solr_query' => $extensionClassesPath . 'Query.php',
	'tx_solr_querymodifierinterface' => $extensionClassesPath . 'QueryModifierInterface.php',
	'tx_solr_search' => $extensionClassesPath . 'Search.php',
	'tx_solr_solrservice' => $extensionClassesPath . 'SolrService.php',
	'tx_solr_substitutepageindexerinterface' => $extensionClassesPath . 'SubstitutePageIndexerInterface.php',
	'tx_solr_util' => $extensionClassesPath . 'Util.php',
	'tx_solr_controller_resultscontroller' => $extensionClassesPath . 'Controller/ResultsController.php',
	'tx_solr_querymodifier_faceting' => $extensionClassesPath . 'querymodifier/Faceting.php',
	'tx_solr_viewhelpers_abstractfacetviewhelper' => $extensionClassesPath . 'ViewHelpers/AbstractFacetViewHelper.php',
	'tx_solr_viewhelpers_abstractviewhelper' => $extensionClassesPath . 'ViewHelpers/AbstractViewHelper.php',
	'tx_solr_viewhelpers_facetdataviewhelper' => $extensionClassesPath . 'ViewHelpers/FacetDataViewHelper.php',
	'tx_solr_viewhelpers_facetnotemptyviewhelper' => $extensionClassesPath . 'ViewHelpers/FacetNotEmptyViewHelper.php',
	'tx_solr_viewhelpers_outputviewhelper' => $extensionClassesPath . 'ViewHelpers/OutputViewHelper.php',
	'tx_solr_viewhelpers_pagebrowserviewhelper' => $extensionClassesPath . 'ViewHelpers/PageBrowserViewHelper.php',
	'tx_solr_viewhelpers_rendersortingviewhelper' => $extensionClassesPath . 'ViewHelpers/RenderSortingViewHelper.php',
	'tx_solr_viewhelpers_usedfacetsviewhelper' => $extensionClassesPath . 'ViewHelpers/UsedFacetsViewHelper.php',
);
?>